---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: thinkblue
# description will be included in the image's metadata
description: uBlue silverblue image for my Thinkpad.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files: 
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        - bat
        - btop
        - eza
        - fastfetch
        - fd-find
        - ghostty
        - ghostty-nautilus
        - gnome-tweaks
        - lm_sensors
        - make
        - micro
        - nautilus-python
        - nethogs
        - ripgrep
        - starship
        - xdg-terminal-exec
        - zoxide
    remove:
      packages:
        - htop
        - firefox
        - firefox-langpacks
        - gnome-classic-session
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-background-logo
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list
        - gnome-software
        - gnome-system-monitor
        - nvtop
        - ptyxis

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal
          - com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Loupe
          - org.gnome.Papers
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
      - notify: false
        scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
